groups:
- name: main
  jobs:
  - Version 
  - Build
  - SonarScan
  - PCFDeploy

resources:
- name: angular-app
  type: git
  source:
    branch: qa
    uri: https://github.com/buggavep/angular-app.git
    private_key: {{github-private-key}}

- name: ci
  type: git
  source:
    branch: qa
    uri: https://github.com/buggavep/ci.git
    private_key: {{github-private-key}}

- name: version-gist
  type: git
  source:
    branch: master
    uri: git@gist.github.com:8138f5263ca1b8952264e4f13fc3a1eb.git
    private_key: {{github-private-key}}

resource_types:

- name: sonar-runner
  type: docker-image
  source:
    repository: cathive/concourse-sonarqube-resource

jobs:
- name: Version
  serial: true
  public: true
  plan:
  - get: angular-app
    trigger: true  
  - get: ci 
  - get: version-gist
  - task: Versioning the App
    file: ci/concourse/version.yml
    input_mapping: {code-repo: angular-app, ci: ci, version-gist: version-gist}
  - put: version-gist
    params: {repository: updated-gist}

- name: Build
  serial: true
  public: true
  plan:
  - get: angular-app
    passed: [Version]
    trigger: true  
  - get: version-gist
  - get: ci 
  - task: Build App
    file: ci/concourse/build.yml
    input_mapping: {code-repo: angular-app, ci: ci, dist: dist, version-gist: version-gist}
    params:
      NEXUS_USERNAME: {{nexus-username}}
      NEXUS_PASSWORD: {{nexus-password}}
      NEXUS_HOST: {{nexus-host}}

- name: SonarScan
  serial: true
  public: true
  plan:
  - get: angular-app
    passed: [Build]
    trigger: true  
  - get: ci 
  - task: Sonar Scan Task
    file: ci/concourse/sonar-scan.yml
    input_mapping: {code-repo: angular-app, ci: ci, dist: dist, version-gist: version-gist}

- name: PCFDeploy
  serial: true
  public: true
  plan:
  - get: angular-app
    passed: [SonarScan]
    trigger: true  
  - get: version-gist
  # - get: artifactory-snapshot
  - get: ci 
  - task: PCF Deploy Task
    file: ci/concourse/cfdeploy.yml
    input_mapping: {code-repo: angular-app, ci: ci, version-gist: version-gist}
    params:
      NEXUS_USERNAME: {{nexus-username}}
      NEXUS_PASSWORD: {{nexus-password}}
      NEXUS_HOST: {{nexus-host}}
      CF_API_ENDPOINT: {{cf-api-endpoint}}
      CF_USERNAME: {{cf-username}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-org}}
      CF_SPACE: {{cf-space}}
      APP_NAME: {{app-name}}