
groups:
- name: main
  jobs:
  - Version-Job  
  - Build-Job

resources:
- name: angular-app
  type: git
  source:
    branch: master
    uri: https://github.com/buggavep/angular-app.git

- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/buggavep/ci.git

- name: version-gist
  type: git
  source:
    branch: master
    uri: git@gist.github.com:8138f5263ca1b8952264e4f13fc3a1eb.git
    private_key: {{github-private-key}}

- name: artifactory-snapshot
  type: artifactory
  source:
    endpoint: http://10.0.0.101:8081/artifactory
    repository: "/libs-snapshot-local/Pivotal"
    regex: "pivotal-(?<version>.*).tar.gz"
    username: admin
    password: password

resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: mborges/artifactory-resource
   
jobs:
- name: Version-Job
  serial: true
  public: true
  plan:
  - get: angular-app
    trigger: true  
  - get: ci 
  - get: version-gist
  - task: Versioning the App
    file: ci/concourse/version.yml
    input_mapping: {code-repo: angular-app, ci: ci, version-gist: version-gist}
  - put: version-gist
    params: {repository: updated-gist}

- name: Build-Job
  serial: true
  public: true
  plan:
  - get: angular-app
    passed: [Version-Job]
    trigger: true  
  - get: version-gist
  - get: ci 
  - get: artifactory
    resource: artifactory-snapshot
  - task: Build App
    file: ci/concourse/build.yml
    input_mapping: {code-repo: angular-app, ci: ci, dist: dist, version-gist: version-gist}
    # params:
    #   ARTIFACTORY_USERNAME: {{artifactory-user}}
    #   ARTIFACTORY_PASSWORD: {{artifactory-password}}
  - put: artifactory-snapshot
    params: 
      file: dist/cibuild-*.tar.gz
