
groups:
- name: main
  jobs:
  - Version-Job  
  - Build-Job

resources:
- name: angular-app
  type: git
  source:
    branch: master
    uri: https://github.com/buggavep/angular-app.git

- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/buggavep/ci.git

jobs:
- name: Version-Job
  serial: true
  public: true
  plan:
  - get: angular-app
    trigger: true  
  - get: ci 
  - task: Versioning the App
    file: ci/concourse/version.yml
    input_mapping: {code-repo: angular-app, ci: ci}

- name: Build-Job
  serial: true
  public: true
  plan:
  - get: angular-app
    passed: [Version-Job]
    trigger: true  
  - get: ci 
  - task: Build App
    file: ci/concourse/build.yml
    input_mapping: {code-repo: angular-app, ci: ci}
