platform: linux
image_resource:
 type: docker-image
 source: 
   repository: node
   tag: "latest"

inputs: 
 - name: code-repo
 - name: ci

outputs:
 - name: dist

run: 
 path: bash
 args:
 - -e
 - -c
 - |
   ls -lrt
   set -o pipefail
   chmod +x ci/scripts/build.sh
   cd code-repo
   ../ci/scripts/build.sh
 
