platform: linux
image_resource:
    type: docker-image
    source: 
      repository: node
      tag: "6"

inputs: 
 - name: code-repo
 - name: ci
 - name: version-gist

outputs:
 - name: dist

run: 
 path: bash
 args:
 - -e
 - -c
 - |
   set -o pipefail
   chmod +x ci/scripts/build.sh
   cd code-repo
   ../ci/scripts/build.sh
 
